openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: A sample API for demonstration
servers:
  - url: http://localhost:3000/api
paths:
  /auth/login:
    post:
      summary: Authenticate a user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string   

    
  /auth/logout:
    delete:
      summary: Logout a user
      tags: [Auth]
      responses:
        '200':
          description: Logout successful
        '500':
          description: Server error during logout

  /students:
    post:
      summary: Register a student
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
                - classname
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                classname:
                  type: string
      responses:
        '200':
          description: Student registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid input data

  

  /teachers:
    post:
      summary: Register a teacher
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
                - classname
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                classname:
                  type: string
      responses:
        '200':
          description: Teacher registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid input data
  
  /teachers:
    get:
      summary: Register a teacher
      tags: [Auth]
      responses:
        '200':
          description: Teacher registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid input data
          
  /techer/avg:
    get:
      summary: Register a teacher
      tags: [Auth]
      responses:
        '200':
          description: Teacher registered successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid input data

 

  /techer/grades:
    post:
      summary: Add a grade
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - studentId
                - testName
                - grade
              properties:
                studentId:
                  type: string
                testName:
                  type: string
                grade:
                  type: number
      responses:
        '200':
          description: Grade added successfully
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid input data
        '404':
          description: Student not found

    get:
      summary: Get grades for a class
      tags: [Auth]
      responses:
        '200':
          description: Grades retrieved successfully
          content:
            application/json:
              schema:
                type: array
                items:
                  type: object
                  # ... properties of grade object
        '400':
          description: Invalid input data