openapi: 3.0.0
info:
  title: My API
  version: 1.0.0
  description: A sample API for demonstration
servers:
  - url: http://localhost:3000/api
paths:
  /auth/login:
    post:
      summary: Authenticate a user
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - password
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid username or password

  /auth/logout:
    delete:
      summary: Logout a user
      tags: [Auth]
      responses:
        '200':
          description: Logout successful
        '500':
          description: Server error during logout
          
  /student:
    post:
      summary: register a techer
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
                - classname
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                classname:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid username or password

  /techer:
    post:
      summary: register a techer
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - username
                - email
                - password
                - classname
              properties:
                username:
                  type: string
                password:
                  type: string
                email:
                  type: string
                classname:
                  type: string
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid username or password
          
  /techer/grades:
    post:
      summary: add a grade
      tags: [Auth]
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              required:
                - studentId
                - testName
                - grade
              properties:
                studentId:
                  type: string
                testName:
                  type: string
                grade:
                  type: number
      responses:
        '200':
          description: Login successful
          content:
            application/json:
              schema:
                type: object
                properties:
                  token:
                    type: string
        '400':
          description: Invalid username or password





# הוסף כאן נתיבים נוספים...